### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by numediaweb**
The jQuery Plugin Registry is in read-only mode

### CODE REVIEW

**Comment by heldr** [comment]
Thank you :package: :smile:

**Comment by zenorocha** [comment]
We should remove this file then: https://github.com/jquery-boilerplate/jquery-boilerplate/blob/master/boilerplate.jquery.json

**Comment by zenorocha** [comment]
Btw, I'm surprised with this change, thanks for letting us know @numediaweb ;D

**Comment by numediaweb** [comment]
@heldr @zenorocha Thanks guys for this awesome boilerplate :)

**Comment by heldr** [comment]
@zenorocha 

Before releasing 3.5.0(since we removed a key file), should we mention alternative installs in Readme?

Ex.:
```shell
npm install jquery-boilerplate/jquery-boilerplate
```

**Comment by zenorocha** [comment]
Yes, I think we can remove the `private` keyword and let people install as `npm install jquery-boilerplate`.

**Pull request merged**
